name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # 수정된 cron 표현식
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # TOKEN을 GITHUB_TOKEN으로 수정
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name imsando
          git config user.email ujm0524@naver.com
          git add -A .
          git commit -m "generated"
          git push
